### ISSUE TITLE
Mongo doesn't start on vagrant up.

### ISSUE THREAD

**Issue by Maximilian118** [beard-crosby/excursions-vagrant#3]
The last couple of times when I run develop on the VM I get this from the backend:

<img width="951" alt="Screenshot 2019-08-09 at 9 56 18 pm" src="https://user-images.githubusercontent.com/45773586/62808643-979bd380-baf0-11e9-9195-7a94b76b5749.png">

I knew what's wrong so I tried all of the following:

<img width="948" alt="Screenshot 2019-08-09 at 9 57 31 pm" src="https://user-images.githubusercontent.com/45773586/62808704-c5811800-baf0-11e9-8427-88d48d843cf3.png">

Then I remembered what I did last time.
After this command, the server starts and I can use it.

<img width="953" alt="Screenshot 2019-08-09 at 9 58 51 pm" src="https://user-images.githubusercontent.com/45773586/62808760-f6614d00-baf0-11e9-9993-311147569253.png">

**Comment by samuelbeard** [comment]
Can you run these commands and see if you still have the issue?

```
# On your vm
exit

# On your mac (Same window)
vagrant halt ; vagrant up ; vagrant ssh

# On the vm when it starts up
mongo
```

Does this work?
