### ISSUE TITLE
Fixing Websocket code 400 issue brakes mongo on Vagrant Up.

### ISSUE THREAD

**Issue by Maximilian118** [beard-crosby/excursions-vagrant#6]
Applying this code to /etc/nginx/sites-available/excursions.test does fix the Websocket 400 error:

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;

However, after applying this code to the vagrant mongo on startup fix you've just pushed, it brakes mongo on start up again:

<img width="952" alt="Screenshot 2019-08-12 at 1 36 48 pm" src="https://user-images.githubusercontent.com/45773586/62865400-52e98580-bd06-11e9-88ab-67762aed87dd.png">

If I restart mongo though and run develop again, the servers run perfectly with no errors:

<img width="951" alt="Screenshot 2019-08-12 at 1 37 12 pm" src="https://user-images.githubusercontent.com/45773586/62865448-757b9e80-bd06-11e9-8c16-31273b7ac850.png">
<img width="952" alt="Screenshot 2019-08-12 at 1 38 58 pm" src="https://user-images.githubusercontent.com/45773586/62865484-8fb57c80-bd06-11e9-9521-7c1ca6ccc3f1.png">

**Comment by samuelbeard** [comment]
Unable to recreate this issue. Can you pull and provision the latest version and see if the problem persists?

**Comment by samuelbeard** [comment]
@Maximilian118
